CREATE TABLE IF NOT EXISTS notaloan_loans (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    balance decimal(12,2) NOT NULL,
    interest_rate decimal(12,2) NOT NULL,
    term INTEGER NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES notaloan_users(id) ON DELETE CASCADE NOT NULL
);